name: ConfigurationPlugin
version: 1.0-SNAPSHOT
main: com.ninjawulf98.com.configurationplugin.ConfigurationPlugin
api-version: 1.13
commands:
  printMessageFromConfig:
    description: Print a message from the config
  setFood:
    description: Sets the food to mango
  Explode:
    description: Boom!