enable: true

message: true
launch-message: '&9Whoosh!'

#Full block name list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
top-block: 'STONE_PRESSURE_PLATE'
under-block: 'REDSTONE_BLOCK'

y-velocity: 2
velocity-multiplier: 3

disable-fall-damage: true