name: TeleportBow
version: ${project.version}
main: com.ninjawulf98.teleportbow.TeleportBow
api-version: 1.13
commands:
  tpbow:
    description: Teleport anywhere with a bow
    usage: /<command>
    permission: tpbow.spawnbow