name: QuarterMaster
version: 1.0-SNAPSHOT
main: com.ninjawulf98.quartermaster.QuarterMaster
api-version: 1.13
commands:
  quartermaster:
    description: Manage and usee the QuarterMaster plugin
    aliases:
      - qm