name: FirstPlugin
version: ${project.version}
main: com.ninjawulf98.firstplugin.FirstPlugin
api-version: 1.13
authors: [ninjawulf98]
description: First plugin from ninjawulf98
website: ninjawulf98.com
