name: ArmorStandGUI
version: ${project.version}
main: com.ninjawulf98.armorstandgui.ArmorStandGUI
api-version: 1.13
commands:
  armorstand:
    description: Create a armor stand
    usage: /<command>
    aliases:
      - as