name: VaultPlugin
version: 1.0-SNAPSHOT
main: com.ninjawulf98.vaultplugin.VaultPlugin
api-version: 1.13
description: A plugin for a player to store their items
commands:
  vault:
    description: Open a vault
    usage: /<command>